version: '3.8'

services:
  mongodb_users:
    image: mongo:latest
    container_name: streamflow_users_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: streamflow_user
      MONGO_INITDB_ROOT_PASSWORD: streamflow_password
    ports:
      - "27018:27017"
    volumes:
      - mongodb_users_data:/data/db

volumes:
  mongodb_users_data: 