version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: streamflow_auth_db
    environment:
      POSTGRES_USER: streamflow_user
      POSTGRES_PASSWORD: streamflow_password
      POSTGRES_DB: streamflow_auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: streamflow_users_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: streamflow_user
      MONGO_INITDB_ROOT_PASSWORD: streamflow_password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  postgres_data:
  mongodb_data: 