version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: streamflow_billing_db
    environment:
      MYSQL_ROOT_PASSWORD: streamflow_password
      MYSQL_DATABASE: streamflow_billing
      MYSQL_USER: streamflow_user
      MYSQL_PASSWORD: streamflow_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: 