version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: streamflow_videos_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: streamflow_user
      MONGO_INITDB_ROOT_PASSWORD: streamflow_password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 