version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: streamflow_auth_db
    environment:
      POSTGRES_USER: streamflow_user
      POSTGRES_PASSWORD: streamflow_password
      POSTGRES_DB: streamflow_auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 